name: Pull Request

on: pull_request

jobs:
  message-check:
    name: Block on fixup commits

    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    steps:
      - uses: xt0rted/block-autosquash-commits-action@v2.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
